export const defaultForm = {
  name: "",
  problem_statement: "",
  priority: "Medium",
  fab_submitted_as: "",
  tool_id: "",
  wiings_order: "",
  part_number: "",
  status: "New Request",
  area: "Buyer/Planner",
  supplier: "AMAT",
  email: "",
};

export const statusDefinitions = [
  "New Request",
  "In Progress",
  "OM Escalated",
  "Waiting 3PL",
  "Closed",
  "Canceled By User",
  "Re-Opened",
  "Waiting Buyer/Supplier",
  "Waiting Customer",
  "Waiting Elevator Repair",
  "Waiting on IT",
  "Waiting Tool Move",
  "Exceptions / Variants",
  "Waiting Chemicals",
  "Waiting Count/Verify",
  "Waiting Delivery Confirmation",
  "Waiting Distribution",
  "Waiting ePart",
  "Waiting Inbound",
  "Waiting IMO",
  "Waiting Inv Control",
  "Waiting Put-away",
  "Waiting Returns",
  "Waiting Shipping",
  "Waiting Si",
  "Waiting Stores",
];

export const areaDefinitions = [
  "Buyer/Planner",
  "Dielectrics",
  "Diffusion",
  "Etch - Dry",
  "Etch - Wet",
  "IMO",
  "Implant",
  "Litho",
  "Metals",
  "Planar",
  "RA4 SORT",
  "RA4 STO",
  "RA4 WLA",
  "Subfab",
  "Thin Films",
  "TSV",
  "VSE",
];

export const supplierDefinitions = [
  "AMAT",
  "ASM",
  "ASML",
  "DSV/UTI",
  "Ebara",
  "Edwards",
  "Hitachi",
  "JX Nippon",
  "KLA",
  "LAM",
  "MSR",
  "Nikon",
  "Not Listed",
  "Pentagon",
  "Praxair/Linde",
  "Quantum Clean",
  "Screen",
  "TEl",
  "UPPRO",
  "VWR",
];
